# Generated by Django 2.2.5 on 2019-10-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20191009_1740'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='chats',
        ),
        migrations.AlterModelTable(
            name='message',
            table='messages',
        ),
    ]
