# Generated by Django 2.2.5 on 2019-09-27 22:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('deviation', 'Deviation'), ('development', 'Development'), ('done', 'Done')], default='processing', max_length=11)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created',),
            },
        ),
    ]
