# Generated by Django 2.2.5 on 2019-09-22 11:42

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('deviation', 'Deviation'), ('development', 'Development'), ('done', 'Done')], default='processing', max_length=10)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField(default=datetime.datetime(2019, 9, 22, 11, 42, 46, 841939, tzinfo=utc))),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
