# Generated by Django 2.2.5 on 2019-09-29 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20190929_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
