# Generated by Django 2.2.5 on 2019-10-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_order_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='managers',
        ),
    ]
