# Generated by Django 2.2.5 on 2019-10-08 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('user_profile', '0008_auto_20191009_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_orders', to='manager.Manager'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
