# Generated by Django 2.2.5 on 2019-10-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20191009_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
