# Generated by Django 2.2.5 on 2019-10-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='manager',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
